# Generated by Django 4.2.2 on 2025-03-24 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contact",
            options={"ordering": ["create_date"]},
        ),
    ]
