# Generated by Django 4.2.2 on 2025-04-13 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0005_alter_contact_subject"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="subject",
            field=models.CharField(default=None, max_length=255),
        ),
    ]
