# Generated by Django 4.2.2 on 2025-03-24 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_post_options_post_author_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(
                default="media/blog/default.jpg", upload_to="media/blog"
            ),
        ),
    ]
