# Generated by Django 4.2.2 on 2025-04-17 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_comments_post_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="comments",
            name="post",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="blog.post"
            ),
            preserve_default=False,
        ),
    ]
