# Generated by Django 4.2.2 on 2025-05-07 23:35

from django.db import migrations
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0008_post_login_require"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="content",
            field=django_summernote.fields.SummernoteTextField(),
        ),
    ]
